apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: ingress-nginx
    repoURL: crossplane-stable/crossplane 
    targetRevision: 1.14.3
    # helm:
    #   values: |-
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true