apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: crossplane 
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.16.0
    # helm:
    #   values: |-
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
