apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: 'bank-vaults'
    targetRevision: "2"
    chart: vault-operator
    #helm:
    #  values: |
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
